extends:
  - stylelint-config-standard-scss

rules:
  indentation: 2
  string-quotes: single
  no-duplicate-selectors: true
  color-hex-case: lower
  color-hex-length: short
  color-named: never
  selector-combinator-space-after: always
  selector-attribute-quotes: always
  selector-attribute-operator-space-before: never
  selector-attribute-operator-space-after: never
  declaration-block-trailing-semicolon: always
  declaration-colon-space-before: never
  declaration-colon-space-after: always
  number-leading-zero: always
  function-url-quotes: always
  font-weight-notation: numeric
  comment-empty-line-before: always
  rule-empty-line-before: always
  at-rule-no-unknown: null
  scss/at-rule-no-unknown: true